### ISSUE TITLE
Feature Request: Keep Menu Item Permissions

### ISSUE THREAD

**Issue by marcbyte64** [Jako/MenuKeeper#2]
We often set custom Permissions for Menu entries but they reset to their default value as soon as the Extra is updated or reinstalled. Would it be possible to keep those as well?

**Comment by Jako** [comment]
This is possible and will go into the next version.

**Comment by Jako** [comment]
Available with [1.1.0](https://github.com/Jako/MenuKeeper/commit/a27afc56f13d2392aba512d1477e5c2294e18343)
